package com.shipwell.rest;

import com.shipwell.constants.ConstantServices;
import com.shipwell.constants.EndPoints;
import com.shipwell.pojos.booking.*;
import com.shipwell.pojos.shipwellAuth.ShipwellAuth;
import com.shipwell.setup.Rest;
import io.restassured.response.Response;

import java.util.*;

public class BookingRest {
    public Response postBooking(ShipwellAuth shipwellAut, String carrier, String shipmentId) {
        return Rest.with()
                .given()
                .header("shipwell-auth", shipwellAut)
                .log()
                .all()
                .contentType(ConstantServices.CONTENT_TYPE_JSON.get())
                .body(bookingInfoRequest(shipmentId))
                .when()
                .post(ConstantServices.URL.get()+EndPoints.END_POINT_CREATE_BOOKING.get()+carrier)
                .then()
                .log()
                .ifError()
                .log()
                .status()
                .extract()
                .response();

    }

    private Booking bookingInfoRequest(String shipmentId) {
        Booking booking = new Booking().setReferences(new ArrayList<ObjReference>(Arrays.asList(new ObjReference()
                .setType("OrderNumber")
                .setValue("Test References"))))
                .setNotes("Coyote-test")
                .setLoad(new ObjLoad()
                        .setStops(new ArrayList<ObjStops>(Arrays.asList(new ObjStops()
                                .setSequence(1)
                                .setInstructions("turn left on the corner")
                                .setRequirements("one")
                                .setLocation(new ObjLocation()
                                        .setLocation_id("Test")
                                        .setName("Test")
                                        .setAddress(new ObjAddress()
                                                .setLine1("123 Main St.")
                                                .setPostal_code("60647")
                                                .setCity_name("Chicago").setState_code("IL").setCountry_code("US"))
                                        .setFacility_id("12345-test")
                                        .setContacts(new ArrayList<ObjContacts>(Arrays.asList(new ObjContacts()
                                                .setFirst_name("Shipwell")
                                                .setLast_name("Pando")
                                                .setPreferred_contact_method("Call")
                                                .setPhone_number("123456789")
                                                .setEmail_address("none"))))
                                        .setGeo_coordinates(Objgeo_coordinates.builder().latitude(3.25).longitude(-15.9).build())
                                        .setTime_zone_offset("America/Chicago"))
                                .setAppointment(new ObjAppointment()
                                        .setFacility_open_date_time_utc("2021-04-23T08:00:00Z")
                                        .setFacility_close_date_time_utc("2021-04-24T08:00:00Z")
                                        .setAppointment_start_date_time_utc("2021-04-23T08:00:00Z")
                                        .setAppointment_end_date_time_utc("2021-04-24T08:00:00Z")
                                        .setConfirm_appointment(false))
                                .setItems(new ArrayList<ObjItems>(Arrays.asList(new ObjItems()
                                        .setId("item-test")
                                        .setQuantity(new ObjValue()
                                                .setValue(120.0)
                                                .setUnit("test-quantity"))
                                        .setWeight(new ObjValue()
                                                .setValue(300.0)
                                                .setUnit("LB"))
                                        .setPackaging_type("DoubleLengthToteBin")
                                        .setCargo_value(300)
                                        .setFreight_class("Undefined")
                                        .setNmfcNumber("fffffffff")
                                        .setCommodity_description("fffffff"))))
                                .setStop_type("PICKUP")
                                .setDrop_trailer(true)
                                .setStop_customer_ref("stop"), new ObjStops()
                                .setSequence(2)
                                .setInstructions("none")
                                .setRequirements("none")
                                .setLocation(new ObjLocation()
                                        .setLocation_id("Test")
                                        .setName("test-2")
                                        .setAddress(new ObjAddress()
                                                .setLine1("123 Downers St.")
                                                .setPostal_code("50313")
                                                .setCity_name("Madison").setState_code("WI").setCountry_code("US"))
                                        .setFacility_id("6789-test")
                                        .setContacts(new ArrayList<ObjContacts>(Arrays.asList(new ObjContacts()
                                                .setFirst_name("String")
                                                .setLast_name("String")
                                                .setPreferred_contact_method("String")
                                                .setPhone_number("String")
                                                .setEmail_address("String"))))
                                        .setGeo_coordinates(Objgeo_coordinates.builder().latitude(3.0).longitude(0.0).build())
                                        .setTime_zone_offset("String"))
                                .setAppointment(new ObjAppointment()
                                        .setFacility_open_date_time_utc("2021-04-25T08:00:00Z")
                                        .setFacility_close_date_time_utc("2021-04-26T08:00:00Z")
                                        .setAppointment_start_date_time_utc("2021-04-25T08:00:00Z")
                                        .setAppointment_end_date_time_utc("2021-04-26T08:00:00Z")
                                        .setConfirm_appointment(false))
                                .setItems(new ArrayList<ObjItems>(Arrays.asList(new ObjItems()
                                        .setId("string")
                                        .setQuantity(new ObjValue()
                                                .setValue(1235.0)
                                                .setUnit("123456"))
                                        .setWeight(new ObjValue()
                                                .setValue(3.0)
                                                .setUnit("LB"))
                                        .setPackaging_type("NotApplicable")
                                        .setCargo_value(123456789)
                                        .setFreight_class("Undefined")
                                        .setNmfcNumber("fffffffff")
                                        .setCommodity_description("fffffff"))))
                                .setStop_type("DROPOFF")
                                .setDrop_trailer(true)
                                .setStop_customer_ref("none"))))
                        .setAccessorials(new ArrayList<ObjAccessorials>(Arrays.asList(new ObjAccessorials()
                                .setType("string")
                                .setCharge(new ObjCharge()
                                        .setAmount(456985)
                                        .setCurrency("string")))))
                        .setLoad_details(new ObjLoadDetails()
                                .setMode("TL")
                                .setRate(new ObjRate()
                                        .setValue(0)
                                        .setCurrency_type("string"))
                                .setEquipment(new ObjEquipment()
                                        .setType("DRY_VAN")
                                        .setHeight(new ObjValue()
                                                .setValue(10.5)
                                                .setUnit("IN"))
                                        .setLength(new ObjValue()
                                                .setValue(9.8)
                                                .setUnit("IN"))
                                        .setWidth(new ObjValue()
                                                .setValue(7.6)
                                                .setUnit("IN")))
                                .setWeight(new ObjValue()
                                        .setValue(5.4)
                                        .setUnit("LB"))
                                .setLoad_distance(new ObjValue()
                                        .setValue(3.2)
                                        .setUnit("string"))
                                .setTemperature_settings(new Objtemperature_settings()
                                        .setMinimum(10.8)
                                        .setMaximum(12.8)
                                        .setUnit("C")
                                        .setPre_cool_temperature(0).setOperating_instructions("Continuous")))).setShipper_id("TESTONLY").setShipment_id(shipmentId).setQuote_id("123456");
        return booking;
    }
}
